### ISSUE TITLE
Single blog post author section

### ISSUE THREAD

**Issue by bradt** [deliciousbrains/new-site#10]
<pre><img src="https://cloud.githubusercontent.com/assets/190095/14712960/a822ac52-07b5-11e6-987c-7237cd8a69f4.png" width="376"></pre>

* [x] Make the headshot smaller and move text up to wrap around it
* [x] Spacing between icons and text
* [x] Title in the email optin needs line height adjustment

**Comment by jacobdubail** [comment]
updated all three items in dev.
