### ISSUE TITLE
Charity logos are tiny on mobile

### ISSUE THREAD

**Issue by bradt** [deliciousbrains/new-site#11]
<pre><img src="https://cloud.githubusercontent.com/assets/190095/14713224/a4fa392c-07b6-11e6-8c6a-c5a00b117cec.png" width="376"></pre>

Should probably be twice as big, if not 3x.

**Comment by timberfoster** [comment]
On mobile we could center/increase size of the logos above these text blocks.

**Comment by jacobdubail** [comment]
Just pushed a fix to center above text for mobile. They're no longer being resized at all (using native size).
