### ISSUE TITLE
Padding is excessive and unbalanced on job listing page on mobile

### ISSUE THREAD

**Issue by bradt** [deliciousbrains/new-site#13]
<pre><img src="https://cloud.githubusercontent.com/assets/190095/14713739/a5767468-07b8-11e6-9645-6ba7b9a4bbe5.png" width="376"></pre>

See https://projects.invisionapp.com/share/DX5OFD5ER#/screens/129024621

**Comment by jacobdubail** [comment]
Fixed. Missed the grid cleanup before uploading. Sorry about that!
