### ISSUE TITLE
404 page missing

### ISSUE THREAD

**Issue by bradt** [deliciousbrains/new-site#14]

**Comment by jacobdubail** [comment]
Did we have a 404 page mockup? I'm not seeing one in the collection.

**Comment by timberfoster** [comment]
Comp: https://invis.io/C85LR0EUQ#/136223101_DeliciousBrains-404

PSD: https://www.dropbox.com/s/hj2pno66v48hu3n/DeliciousBrains-404.psd?dl=0

**Comment by jacobdubail** [comment]
Thanks Tim. I'll update this now.

**Comment by bradt** [comment]
What collection are you looking at? I just forwarded you an email containing an Adobe CC link to the PSDs I sent a while back. It contains the 404 page.

**Comment by jacobdubail** [comment]
Thanks Brad. I must not have downloaded all of those updated PSDs. My bad. Thanks for resending.

**Comment by jacobdubail** [comment]
Here you go: http://dbrains.jacobdubail.com/404.php
