### ISSUE TITLE
Screenshot with accordion shrinking to comical size

### ISSUE THREAD

**Issue by bradt** [deliciousbrains/new-site#15]
This looks ridiculous on my tablet (768x1024) but also doesn't look great a slightly larger screen sizes. It starts to look funny at 1060 and lower.

![screenshot_2016-04-21-14-52-16](https://cloud.githubusercontent.com/assets/190095/14719720/2de2a7b6-07d4-11e6-9cd2-eb0c48fcd636.png)

@timberfoster What would you suggest here?

**Comment by jacobdubail** [comment]
I can change the point at which the image displays inline with the content. Right now I believe it switches at 768. We could bump that up to 1024 or any size you'd like (1060px for instance).

**Comment by jacobdubail** [comment]
I've updated this functionality to swap at 1060px. Let me know if that looks better to you. Happy to keep iterating here.
