### ISSUE TITLE
9.7-inch tablet issues (portrait: 768x1024)

### ISSUE THREAD

**Issue by bradt** [deliciousbrains/new-site#16]
* [x] Spacing issue between button and product title
* [x] Greeting text has some ugly line breaks

![screenshot_2016-04-21-14-51-37](https://cloud.githubusercontent.com/assets/190095/14719716/2de184ee-07d4-11e6-977d-205e9da1377a.png)

* [x] Top borders on tweets are not visible

![screenshot_2016-04-21-14-52-03](https://cloud.githubusercontent.com/assets/190095/14719719/2de29da2-07d4-11e6-9623-1a110013d5ef.png)

* [x] We could make better use of the screen real estate here, no need for so much padding on the sides:

![screenshot_2016-04-21-14-52-44](https://cloud.githubusercontent.com/assets/190095/14719721/2dea07a4-07d4-11e6-9f19-5bd522ee0857.png)

* [x] Should be obvious the problem here:

![screenshot_2016-04-21-15-02-18](https://cloud.githubusercontent.com/assets/190095/14719717/2de1e6d2-07d4-11e6-93c6-afa08e03c740.png)

**Comment by jacobdubail** [comment]
Pushed some changes to github and dev server. Let me know if that looks better for you.
