### ISSUE TITLE
Footer padding

### ISSUE THREAD

**Issue by bradt** [deliciousbrains/new-site#17]
Please see mockups for correct style.

Seeing this on desktop, a lack of padding to the right of the Latest Posts content:

![image](https://cloud.githubusercontent.com/assets/190095/14720314/4b5ca47e-07d7-11e6-9632-084508e56595.png)

On tablet, there's even less padding:

![screenshot_2016-04-21-15-03-57](https://cloud.githubusercontent.com/assets/190095/14719718/2de2b062-07d4-11e6-9030-ec808bc90223.png)

**Comment by jacobdubail** [comment]
I've added more spacing here for mobile and desktop. Let me know how that looks.

**Comment by bradt** [comment]
Why add more padding for mobile? The report was for table and desktop.

**Comment by jacobdubail** [comment]
Great question that doesn't have a great answer... Fixed that. Hopefully it looks a bit better now. I also made the comment count a link. I believe you had asked for that previously. If not, super easy to revert.
