### ISSUE TITLE
Missing special footer for the blog section

### ISSUE THREAD

**Issue by bradt** [deliciousbrains/new-site#18]
From the mockups:

![image](https://cloud.githubusercontent.com/assets/190095/14721213/ab2f77c4-07db-11e6-87ac-37dea5a443db.png)

This was highlighted in [the few notes I gave you at the start of the project](https://docs.google.com/document/d/1yTzWV7cl_6WE03qQE_Fe2CnuErxaJxp8rN48TBq7Avs/edit):

> **Blog-Aggregate**
> Notice that the footer is a little different here. I would like this changed a little: the area with the Plugins title and stars can just be the same slate colour as the section below it and make the title and stars white. Obviously the same applies for all other mockups where this footer appears.

**Comment by jacobdubail** [comment]
Completed screwed that one up, didn't I? I'll get this added right away.

**Comment by jacobdubail** [comment]
Added to dev and github.

**Comment by bradt** [comment]
For the third time...

> **Blog-Aggregate**
> Notice that the footer is a little different here. I would like this changed a little: the area with the Plugins title and stars can just be the same slate colour as the section below it and make the title and stars white. Obviously the same applies for all other mockups where this footer appears.

Also, "Plugins" should be "PLUGINS" like the mockup.

**Comment by jacobdubail** [comment]
My bad. I clearly don't read well... Just uploaded that fix for you.
