### ISSUE TITLE
Charity logos are distorted

### ISSUE THREAD

**Issue by bradt** [deliciousbrains/new-site#2]
![image](https://cloud.githubusercontent.com/assets/190095/14686749/95c9edae-0710-11e6-8405-84e77840f31d.png)

**Comment by jacobdubail** [comment]
I've removed the set width on these images. They'll now always display at their native dimensions.

**Comment by bradt** [comment]
Did you upload it? I'm still seeing the issue.

**Comment by jacobdubail** [comment]
I did upload, but now the issue is that each image is a different width, which breaks the alignment of the accompanying paragraphs. Will get this fixed up shortly.

**Comment by jacobdubail** [comment]
I had to set a max-width on these guys so that the columns line up correctly. I set the max-width as close to the average native image width as I could. Let me know if you'd like to see any other tweaks here.
