### ISSUE TITLE
[MOBILE] - Center buttons - line height

### ISSUE THREAD

**Issue by timberfoster** [deliciousbrains/new-site#21]
![2016-04-22 15 59 41](https://cloud.githubusercontent.com/assets/1993726/14752691/2b6bb8aa-08a7-11e6-98fc-32b7f06d0103.png)

- Can we center the "Watch demo" and "Get plugin" buttons? When inspecting in mobile on my computer they are centered but on my phone they are left aligned?
- The line height on the "Migration can be..." headline needs to be taken down a bit too, the spacing is to big. Around 1.1 or 1.2 line-height would do it.

**Comment by jacobdubail** [comment]
I've tested on an iPhone6 and this appears to be fixed now.

**Comment by timberfoster** [comment]
Looks good
