### ISSUE TITLE
[MOBILE] - View Demo buttons on Product landing pages

### ISSUE THREAD

**Issue by timberfoster** [deliciousbrains/new-site#22]
![2016-04-22 15 59 55](https://cloud.githubusercontent.com/assets/1993726/14752855/fda168e2-08a7-11e6-9b02-2adcec79336a.png)
When a user clicks on the "Watch Demo" button can we make that video play right away, rather then opening in a lightbox and having to click a second time? Can we skip that second step on mobile?

**Comment by jacobdubail** [comment]
The code that renders on in the DOM includes the youtube autoplay=1 parameter, so most devices should autoplay the video, but it looks like most devices actually block this feature for data usage reasons: http://stackoverflow.com/questions/8141652/youtube-embedded-video-autoplay-feature-not-working-in-iphone/8142187#8142187
