### ISSUE TITLE
[MOBILE] - 100% Money back guarantee stars

### ISSUE THREAD

**Issue by timberfoster** [deliciousbrains/new-site#23]
![2016-04-22 16 02 14](https://cloud.githubusercontent.com/assets/1993726/14752859/05bc0776-08a8-11e6-9b8a-d62d5049ab45.png)
The spacing of the stars against the sides looks odd on mobile. Can we just put 1 star underneath the copy centered on mobile?

**Comment by jacobdubail** [comment]
Updated. Will push this to dev in a batch when I finish all issues.
