### ISSUE TITLE
[MOBILE] - Style search input on Documentation pages

### ISSUE THREAD

**Issue by timberfoster** [deliciousbrains/new-site#24]
![2016-04-22 16 03 15](https://cloud.githubusercontent.com/assets/1993726/14752923/6a38259a-08a8-11e6-9f6b-fb2bd16819d9.png)
Shouldn't be full rounded edges, should be consistent with other inputs. (See newsletter signup input as an example)

**Comment by jacobdubail** [comment]
Which device is this? I'm overriding border-radius which should address ios 8+ and android 4+ if I'm not mistaken. It's a search input instead of a text input.

**Comment by bradt** [comment]
Are you sure `type="search"` can be styled on iOS? It didn't used to allow it.

**Comment by bradt** [comment]
We'll take care of this in theme integration if need be.
