### ISSUE TITLE
See Pricing / Get Plugin links

### ISSUE THREAD

**Issue by timberfoster** [deliciousbrains/new-site#29]
Again, just don't this to be missed. There's still a few of these buttons that aren't connected to the pricing pages.

**Comment by jacobdubail** [comment]
When a visitor is on the Migrate page and hits the Get Plugin link, where will that actually go? I assumed that would go to some kind of cart page. Or will it just link to the Pricing page?

**Comment by bradt** [comment]
We'll take care of this in theme integration.
