### ISSUE TITLE
Product branding missing on mobile

### ISSUE THREAD

**Issue by bradt** [deliciousbrains/new-site#3]
<img src="https://cloud.githubusercontent.com/assets/190095/14693069/3d400c28-0732-11e6-89ff-a37976b8de03.png" width="376">

Is the background video supposed to be playing on mobile. It's not playing on my Galaxy S6. In any case, I don't think we should bother playing the background video on mobile but instead follow the wireframes here, replacing the play button with the product icon and buttons:

![image](https://cloud.githubusercontent.com/assets/190095/14692930/1af07e06-0731-11e6-807d-92d1fdc1ddfb.png)

**Comment by bradt** [comment]
@timberfoster You have any opinions on this?

**Comment by timberfoster** [comment]
@bradt I agree, let's get this inline with the wireframes, video is to heavy to play in the background on mobile. Add the product icon, and CTA buttons to "Watch Demo" and "Get Plugin"

**Comment by jacobdubail** [comment]
Cleaned up both product homepages and pushed to dev.
