### ISSUE TITLE
Screenshot placement/spacing

### ISSUE THREAD

**Issue by bradt** [deliciousbrains/new-site#4]
<pre><img src="https://cloud.githubusercontent.com/assets/190095/14712326/06bbb7f2-07b3-11e6-995f-07cfe11a37b7.png" width="376"></pre>

@timberfoster The screenshot should probably hug the gray background here eh? Should probably be a bit tighter to the button too. Btw, you can see this for yourself by going to http://dbrains.jacobdubail.com/migrate.php on your phone.

**Comment by timberfoster** [comment]
Agreed. Probably need about 30px between the button and product shot. And the product shot should be touching the gray "How it Works' background.

**Comment by jacobdubail** [comment]
Updated.
