### ISSUE TITLE
Twitter avatars on their own line

### ISSUE THREAD

**Issue by bradt** [deliciousbrains/new-site#5]
<img src="https://cloud.githubusercontent.com/assets/190095/14712446/8f50e92a-07b3-11e6-90c9-b2276e785dba.png" width="376">

I think it might look better if the name, username, and tweet content were up on the same line as the avatar and the text would just wrap around it. And if the name and username are too long to fit on their own line together, they could break onto 2 lines. @timberfoster Thoughts?

**Comment by timberfoster** [comment]
Agreed. For mobile this will shorten the height of the testimonials.

**Comment by bradt** [comment]
I'm also seeing this on the desktop:

![image](https://cloud.githubusercontent.com/assets/190095/14719237/86c5cd02-07d1-11e6-8a92-91f774aeaad5.png)

But the avatar should be aligned top like the mockups:

![image](https://cloud.githubusercontent.com/assets/190095/14719254/a3fbd178-07d1-11e6-8c9e-dd62942366d7.png)

**Comment by jacobdubail** [comment]
Fixed!

**Comment by bradt** [comment]
I'm seeing this on desktop:

![image](https://cloud.githubusercontent.com/assets/190095/14721545/55befd6c-07dd-11e6-99a0-a7bc899c3b5b.png)

Please test all your breakpoints before saying it's fixed.

**Comment by jacobdubail** [comment]
believe it or not, I did, but I didn't test in Safari. Fixed that now.
