### ISSUE TITLE
Stars and button shouldn't be part of the slider

### ISSUE THREAD

**Issue by bradt** [deliciousbrains/new-site#6]
<pre><img src="https://cloud.githubusercontent.com/assets/190095/14712554/face91d4-07b3-11e6-950b-245d6c7dd226.png" width="376"></pre>

I find it kind of strange that the stars and the button swipe as well. I think it would be better if they stayed fixed and just the quote bit moved. That would mean we should move the pagination indicators (little dashes) up above the button too. Thoughts @timberfoster?

**Comment by timberfoster** [comment]
Agreed, keep the stars and button static, everything stays static except the quote itself.

**Comment by jacobdubail** [comment]
Fixed.
